# coding: utf-8

"""
    FastFuels API

    A JSON API for creating, editing, and retrieving 3D fuels data for next generation fire behavior models.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FBFM40(str, Enum):
    """
    FBFM40
    """

    """
    allowed enum values
    """
    NB1 = 'NB1'
    NB2 = 'NB2'
    NB3 = 'NB3'
    NB8 = 'NB8'
    NB9 = 'NB9'
    GR1 = 'GR1'
    GR2 = 'GR2'
    GR3 = 'GR3'
    GR4 = 'GR4'
    GR5 = 'GR5'
    GR6 = 'GR6'
    GR7 = 'GR7'
    GR8 = 'GR8'
    GR9 = 'GR9'
    GS1 = 'GS1'
    GS2 = 'GS2'
    GS3 = 'GS3'
    GS4 = 'GS4'
    SH1 = 'SH1'
    SH2 = 'SH2'
    SH3 = 'SH3'
    SH4 = 'SH4'
    SH5 = 'SH5'
    SH6 = 'SH6'
    SH7 = 'SH7'
    SH8 = 'SH8'
    SH9 = 'SH9'
    TU1 = 'TU1'
    TU2 = 'TU2'
    TU3 = 'TU3'
    TU4 = 'TU4'
    TU5 = 'TU5'
    TL1 = 'TL1'
    TL2 = 'TL2'
    TL3 = 'TL3'
    TL4 = 'TL4'
    TL5 = 'TL5'
    TL6 = 'TL6'
    TL7 = 'TL7'
    TL8 = 'TL8'
    TL9 = 'TL9'
    SB1 = 'SB1'
    SB2 = 'SB2'
    SB3 = 'SB3'
    SB4 = 'SB4'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FBFM40 from a JSON string"""
        return cls(json.loads(json_str))


