# coding: utf-8

"""
    FastFuels API

    A JSON API for creating, editing, and retrieving 3D fuels data for next generation fire behavior models.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SurfaceGridLandfireFCCSGroup(str, Enum):
    """
    The size class groups available for the FCCS fuel model. FCCS supports 1-hour, 10-hour, and 100-hour timelag fuels only.
    """

    """
    allowed enum values
    """
    ONEHOUR = 'oneHour'
    TENHOUR = 'tenHour'
    HUNDREDHOUR = 'hundredHour'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SurfaceGridLandfireFCCSGroup from a JSON string"""
        return cls(json.loads(json_str))


