# coding: utf-8

"""
    FastFuels API

    A JSON API for creating, editing, and retrieving 3D fuels data for next generation fire behavior models.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from fastfuels_sdk.client_library.models.surface_grid_modification_fbfm_condition import SurfaceGridModificationFBFMCondition
from fastfuels_sdk.client_library.models.surface_grid_modification_fuel_height_condition import SurfaceGridModificationFuelHeightCondition
from fastfuels_sdk.client_library.models.surface_grid_modification_fuel_load_condition import SurfaceGridModificationFuelLoadCondition
from fastfuels_sdk.client_library.models.surface_grid_modification_fuel_moisture_condition import SurfaceGridModificationFuelMoistureCondition
from fastfuels_sdk.client_library.models.surface_grid_modification_spatial_condition import SurfaceGridModificationSpatialCondition
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

SURFACEGRIDMODIFICATIONCONDITION_ANY_OF_SCHEMAS = ["SurfaceGridModificationFBFMCondition", "SurfaceGridModificationFuelHeightCondition", "SurfaceGridModificationFuelLoadCondition", "SurfaceGridModificationFuelMoistureCondition", "SurfaceGridModificationSpatialCondition"]

class SurfaceGridModificationCondition(BaseModel):
    """
    A condition for the surface grid modification. Can be either an attribute-based condition (checking attribute values) or a spatial condition (checking geographic location).
    """

    # data type: SurfaceGridModificationSpatialCondition
    anyof_schema_1_validator: Optional[SurfaceGridModificationSpatialCondition] = None
    # data type: SurfaceGridModificationFBFMCondition
    anyof_schema_2_validator: Optional[SurfaceGridModificationFBFMCondition] = None
    # data type: SurfaceGridModificationFuelLoadCondition
    anyof_schema_3_validator: Optional[SurfaceGridModificationFuelLoadCondition] = None
    # data type: SurfaceGridModificationFuelHeightCondition
    anyof_schema_4_validator: Optional[SurfaceGridModificationFuelHeightCondition] = None
    # data type: SurfaceGridModificationFuelMoistureCondition
    anyof_schema_5_validator: Optional[SurfaceGridModificationFuelMoistureCondition] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[SurfaceGridModificationFBFMCondition, SurfaceGridModificationFuelHeightCondition, SurfaceGridModificationFuelLoadCondition, SurfaceGridModificationFuelMoistureCondition, SurfaceGridModificationSpatialCondition]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "SurfaceGridModificationFBFMCondition", "SurfaceGridModificationFuelHeightCondition", "SurfaceGridModificationFuelLoadCondition", "SurfaceGridModificationFuelMoistureCondition", "SurfaceGridModificationSpatialCondition" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = SurfaceGridModificationCondition.model_construct()
        error_messages = []
        # validate data type: SurfaceGridModificationSpatialCondition
        if not isinstance(v, SurfaceGridModificationSpatialCondition):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SurfaceGridModificationSpatialCondition`")
        else:
            return v

        # validate data type: SurfaceGridModificationFBFMCondition
        if not isinstance(v, SurfaceGridModificationFBFMCondition):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SurfaceGridModificationFBFMCondition`")
        else:
            return v

        # validate data type: SurfaceGridModificationFuelLoadCondition
        if not isinstance(v, SurfaceGridModificationFuelLoadCondition):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SurfaceGridModificationFuelLoadCondition`")
        else:
            return v

        # validate data type: SurfaceGridModificationFuelHeightCondition
        if not isinstance(v, SurfaceGridModificationFuelHeightCondition):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SurfaceGridModificationFuelHeightCondition`")
        else:
            return v

        # validate data type: SurfaceGridModificationFuelMoistureCondition
        if not isinstance(v, SurfaceGridModificationFuelMoistureCondition):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SurfaceGridModificationFuelMoistureCondition`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in SurfaceGridModificationCondition with anyOf schemas: SurfaceGridModificationFBFMCondition, SurfaceGridModificationFuelHeightCondition, SurfaceGridModificationFuelLoadCondition, SurfaceGridModificationFuelMoistureCondition, SurfaceGridModificationSpatialCondition. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[SurfaceGridModificationSpatialCondition] = None
        try:
            instance.actual_instance = SurfaceGridModificationSpatialCondition.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[SurfaceGridModificationFBFMCondition] = None
        try:
            instance.actual_instance = SurfaceGridModificationFBFMCondition.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[SurfaceGridModificationFuelLoadCondition] = None
        try:
            instance.actual_instance = SurfaceGridModificationFuelLoadCondition.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[SurfaceGridModificationFuelHeightCondition] = None
        try:
            instance.actual_instance = SurfaceGridModificationFuelHeightCondition.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[SurfaceGridModificationFuelMoistureCondition] = None
        try:
            instance.actual_instance = SurfaceGridModificationFuelMoistureCondition.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into SurfaceGridModificationCondition with anyOf schemas: SurfaceGridModificationFBFMCondition, SurfaceGridModificationFuelHeightCondition, SurfaceGridModificationFuelLoadCondition, SurfaceGridModificationFuelMoistureCondition, SurfaceGridModificationSpatialCondition. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], SurfaceGridModificationFBFMCondition, SurfaceGridModificationFuelHeightCondition, SurfaceGridModificationFuelLoadCondition, SurfaceGridModificationFuelMoistureCondition, SurfaceGridModificationSpatialCondition]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


