# coding: utf-8

"""
    FastFuels API

    A JSON API for creating, editing, and retrieving 3D fuels data for next generation fire behavior models.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from fastfuels_sdk.client_library.models.cr_modification_condition import CRModificationCondition
from fastfuels_sdk.client_library.models.dia_modification_condition import DIAModificationCondition
from fastfuels_sdk.client_library.models.ht_modification_condition import HTModificationCondition
from fastfuels_sdk.client_library.models.spcd_modification_condition import SPCDModificationCondition
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

TREEINVENTORYMODIFICATIONCONDITIONSINNER_ANY_OF_SCHEMAS = ["CRModificationCondition", "DIAModificationCondition", "HTModificationCondition", "SPCDModificationCondition"]

class TreeInventoryModificationConditionsInner(BaseModel):
    """
    TreeInventoryModificationConditionsInner
    """

    # data type: SPCDModificationCondition
    anyof_schema_1_validator: Optional[SPCDModificationCondition] = None
    # data type: HTModificationCondition
    anyof_schema_2_validator: Optional[HTModificationCondition] = None
    # data type: DIAModificationCondition
    anyof_schema_3_validator: Optional[DIAModificationCondition] = None
    # data type: CRModificationCondition
    anyof_schema_4_validator: Optional[CRModificationCondition] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[CRModificationCondition, DIAModificationCondition, HTModificationCondition, SPCDModificationCondition]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "CRModificationCondition", "DIAModificationCondition", "HTModificationCondition", "SPCDModificationCondition" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = TreeInventoryModificationConditionsInner.model_construct()
        error_messages = []
        # validate data type: SPCDModificationCondition
        if not isinstance(v, SPCDModificationCondition):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SPCDModificationCondition`")
        else:
            return v

        # validate data type: HTModificationCondition
        if not isinstance(v, HTModificationCondition):
            error_messages.append(f"Error! Input type `{type(v)}` is not `HTModificationCondition`")
        else:
            return v

        # validate data type: DIAModificationCondition
        if not isinstance(v, DIAModificationCondition):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DIAModificationCondition`")
        else:
            return v

        # validate data type: CRModificationCondition
        if not isinstance(v, CRModificationCondition):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CRModificationCondition`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in TreeInventoryModificationConditionsInner with anyOf schemas: CRModificationCondition, DIAModificationCondition, HTModificationCondition, SPCDModificationCondition. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[SPCDModificationCondition] = None
        try:
            instance.actual_instance = SPCDModificationCondition.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[HTModificationCondition] = None
        try:
            instance.actual_instance = HTModificationCondition.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[DIAModificationCondition] = None
        try:
            instance.actual_instance = DIAModificationCondition.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[CRModificationCondition] = None
        try:
            instance.actual_instance = CRModificationCondition.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into TreeInventoryModificationConditionsInner with anyOf schemas: CRModificationCondition, DIAModificationCondition, HTModificationCondition, SPCDModificationCondition. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CRModificationCondition, DIAModificationCondition, HTModificationCondition, SPCDModificationCondition]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


