# coding: utf-8

"""
    FastFuels API

    A JSON API for creating, editing, and retrieving 3D fuels data for next generation fire behavior models.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from fastfuels_sdk.client_library.models.cr_modification_action import CRModificationAction
from fastfuels_sdk.client_library.models.dia_modification_action import DIAModificationAction
from fastfuels_sdk.client_library.models.ht_modification_action import HTModificationAction
from fastfuels_sdk.client_library.models.remove_modification_action import RemoveModificationAction
from fastfuels_sdk.client_library.models.spcd_modification_action import SPCDModificationAction
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

TREEINVENTORYMODIFICATIONACTIONSINNER_ANY_OF_SCHEMAS = ["CRModificationAction", "DIAModificationAction", "HTModificationAction", "RemoveModificationAction", "SPCDModificationAction"]

class TreeInventoryModificationActionsInner(BaseModel):
    """
    TreeInventoryModificationActionsInner
    """

    # data type: SPCDModificationAction
    anyof_schema_1_validator: Optional[SPCDModificationAction] = None
    # data type: HTModificationAction
    anyof_schema_2_validator: Optional[HTModificationAction] = None
    # data type: DIAModificationAction
    anyof_schema_3_validator: Optional[DIAModificationAction] = None
    # data type: CRModificationAction
    anyof_schema_4_validator: Optional[CRModificationAction] = None
    # data type: RemoveModificationAction
    anyof_schema_5_validator: Optional[RemoveModificationAction] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[CRModificationAction, DIAModificationAction, HTModificationAction, RemoveModificationAction, SPCDModificationAction]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "CRModificationAction", "DIAModificationAction", "HTModificationAction", "RemoveModificationAction", "SPCDModificationAction" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = TreeInventoryModificationActionsInner.model_construct()
        error_messages = []
        # validate data type: SPCDModificationAction
        if not isinstance(v, SPCDModificationAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SPCDModificationAction`")
        else:
            return v

        # validate data type: HTModificationAction
        if not isinstance(v, HTModificationAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `HTModificationAction`")
        else:
            return v

        # validate data type: DIAModificationAction
        if not isinstance(v, DIAModificationAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DIAModificationAction`")
        else:
            return v

        # validate data type: CRModificationAction
        if not isinstance(v, CRModificationAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CRModificationAction`")
        else:
            return v

        # validate data type: RemoveModificationAction
        if not isinstance(v, RemoveModificationAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RemoveModificationAction`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in TreeInventoryModificationActionsInner with anyOf schemas: CRModificationAction, DIAModificationAction, HTModificationAction, RemoveModificationAction, SPCDModificationAction. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[SPCDModificationAction] = None
        try:
            instance.actual_instance = SPCDModificationAction.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[HTModificationAction] = None
        try:
            instance.actual_instance = HTModificationAction.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[DIAModificationAction] = None
        try:
            instance.actual_instance = DIAModificationAction.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[CRModificationAction] = None
        try:
            instance.actual_instance = CRModificationAction.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[RemoveModificationAction] = None
        try:
            instance.actual_instance = RemoveModificationAction.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into TreeInventoryModificationActionsInner with anyOf schemas: CRModificationAction, DIAModificationAction, HTModificationAction, RemoveModificationAction, SPCDModificationAction. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CRModificationAction, DIAModificationAction, HTModificationAction, RemoveModificationAction, SPCDModificationAction]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


