name: Tests
on:
  pull_request:
    branches:
      - main

env:
    FASTFUELS_API_KEY: ${{ secrets.FASTFUELS_API_KEY }}

jobs:
  test:
    name: Test ${{matrix.os }} - ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        env:
          - requirements/tests-38.yml
          - requirements/tests-39.yml
          - requirements/tests-310.yml
          - requirements/tests-311.yml

    steps:
      - uses: actions/checkout@v3
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ${{ matrix.env }}
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Log Environment
        run: |
          python -V
          conda info
          conda list

      - name: Test ${{ matrix.env }}
        run: |
          cd tests/
          pytest