name: Test on Cron Schedule
on:
  schedule:
    # At 00:00 on Monday.
    - cron: '0 0 * * 1'

env:
    FASTFUELS_API_KEY: ${{ secrets.FASTFUELS_API_KEY }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test_requirements.txt
    - name: Run pytest
      env:
        TEST_ENV: local
      run: |
        cd tests/
        pytest
